In [1]:
pwd

'C:\\Users\\iibm\\Desktop\\Gulshan'

In [2]:
print("Gulshan")

Gulshan


In [5]:
print('''Gulshan''')

Gulshan


In [4]:
print('Gulshan')

Gulshan


In [7]:
print('Gulshan\'Kumar\'')

Gulshan'Kumar'


In [8]:
print('''
Gulshan
Kumar
ZHI
''')


Gulshan
Kumar
ZHI



# Arithmatic Operator

### Plus

In [9]:
2+5

7

In [11]:
5+5

10

In [12]:
9-5

4

In [14]:
5*2

10

In [15]:
4/2

2.0

In [16]:
2e2

200.0

In [17]:
5*5+8*2

41

In [18]:
(5+5)*2

20

In [19]:
x=20
x

20

In [20]:
print(x)

20


In [21]:
print(type(x))

<class 'int'>


In [24]:
s= 'workshop'
s

'workshop'

## Slicing & Indexing

#### s[start:end:step]

In [25]:
s[:]

'workshop'

In [26]:
s[::]

'workshop'

In [27]:
s[5]

'h'

In [28]:
s[:5]

'works'

In [29]:
s[3:]

'kshop'

In [30]:
s[::2]

'wrso'

In [31]:
s[:-1]

'worksho'

In [32]:
s[:-5]

'wor'

In [33]:
s[::-1]

'pohskrow'

## Methods

In [34]:
s.upper()

'WORKSHOP'

In [35]:
s=s.upper()
s

'WORKSHOP'

### Split

In [36]:
'data'.split()

['data']

In [38]:
'A B C D E F G'.split()

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [41]:
'A B C D E F G'.split('C')

['A B ', ' D E F G']

In [42]:
s.split()

['WORKSHOP']

In [45]:
s.split('K')

['WOR', 'SHOP']

### Print Property

In [49]:
Name='Gulshan'
Class=12
print(Name+str(Class))

Gulshan12


### Formating

In [52]:
print("This is a %s pen"%('blue'))

This is a blue pen


### List

In [55]:
my_list='a b c d'.split()
my_list

['a', 'b', 'c', 'd']

In [60]:
my_list=['a',5,2,3]
my_list

['a', 5, 2, 3]

In [57]:
type(my_list)

list

In [68]:
print(type(my_list))

<class 'list'>


### slicing and Indexing

In [63]:
my_list[1]

5

In [65]:
my_list[0:2]

['a', 5]

In [66]:
my_list[0:3:1]

['a', 5, 2]

In [67]:
my_list[0:3:2]

['a', 2]

In [69]:
my_list*2

['a', 5, 2, 3, 'a', 5, 2, 3]

In [73]:
my_list=my_list + ['a']
my_list

['a', 5, 2, 3, 'a', 'a', 'a', 'a']

### List Method

In [75]:
I=[1,2,3,4,5]
I

[1, 2, 3, 4, 5]

In [76]:
I.append('A B C'.split())
I

[1, 2, 3, 4, 5, ['A', 'B', 'C']]

In [81]:
I.append('G')
I

[1, 2, 3, 4, 5, ['A', 'B', 'C'], 'A', 'Gulshan', 'G']

In [80]:
print(type(my_list))

<class 'list'>


In [87]:
I.pop(2)
I

[1, 2, 4, 5, ['A', 'B', 'C'], 'A', 'Gulshan', 'G']

In [88]:
l=[1,2,5,6,8,7]

In [89]:
l

[1, 2, 5, 6, 8, 7]

In [90]:
l.pop(3)

6

In [98]:
m1=[1,2,3]
m2=[4,5,6]
m3=[7,8,9]

In [99]:
matrix=[m1,m2,m3]

In [100]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [101]:
type (matrix)

list

In [102]:
matrix[1][0]

4

In [103]:
len(matrix)

3

### Tuple

In [105]:
t1=(1,2,3)
t1

(1, 2, 3)

In [106]:
type(t1)

tuple

In [107]:
print(type(t1))

<class 'tuple'>


In [108]:
m2=[1,2,3]
m2[2]=5
m2

[1, 2, 5]

In [109]:
t1[1]

2

In [110]:
t1[-1]

3

### Tuple Method

In [111]:
t1.index(2)

1

In [112]:
t1

(1, 2, 3)

In [113]:
t1.index(2)

1

In [116]:
t1.count(3)

1

### Dictionary

In [117]:
dic1={1:'a',2:'b',3:'c'}
dic1

{1: 'a', 2: 'b', 3: 'c'}

In [118]:
type(dic1)

dict

In [119]:
print(type(dic1))

<class 'dict'>


In [120]:
dic1[2]

'b'

In [121]:
dic1[1]

'a'

In [123]:
dic1[4]='Gulshan'
dic1

{1: 'a', 2: 'b', 3: 'c', 4: 'Gulshan'}

### Nested Dictionary

In [127]:
dic1={1: 'a', 2: 'b','key1':{4: 'e', 5: 'Gulshan', 6: 'g'},3:'c'}
dic1

{1: 'a', 2: 'b', 'key1': {4: 'e', 5: 'Gulshan', 6: 'g'}, 3: 'c'}

In [131]:
dic1['key1']

{4: 'e', 5: 'Gulshan', 6: 'g'}

In [144]:
dic1['key1'][5]

'Gulshan'

In [145]:
dic1['key1'][5][3]

's'

### Method

In [136]:
dic1.keys()

dict_keys([1, 2, 'key1', 3])

In [137]:
dic1.values()

dict_values(['a', 'b', {4: 'e', 5: 'Gulshan', 6: 'g'}, 'c'])

In [138]:
dic1.items()

dict_items([(1, 'a'), (2, 'b'), ('key1', {4: 'e', 5: 'Gulshan', 6: 'g'}), (3, 'c')])

### Set

#### unorder Collection

In [139]:
x=set()
x

set()

In [140]:
type(x)

set

In [141]:
print(type(x))

<class 'set'>


In [142]:
x.add(1)
x

{1}

In [149]:
list1=[1,2,3,1,2,3,1,2,3,]
list1

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [150]:
set(list1)

{1, 2, 3}

### Boolean

In [151]:
True

True

In [152]:
False

False

In [154]:
None

###### Reassign 'hello' in this nested list to say 'goodbye' instead:
list3 = [1,2,[3,4,'hello']]

In [155]:
list3 = [1,2,[3,4,'hello']]
list3

[1, 2, [3, 4, 'hello']]

In [156]:
list3[2][2]

'hello'

In [157]:
list3[2][2]='Goodbye'
list3

[1, 2, [3, 4, 'Goodbye']]

In [160]:
list3[2]

[3, 4, 'Goodbye']

###### list5 = [1,2,2,33,4,4,11,22,3,3,2] create a set from the variable list5.

In [176]:
list5=[1,2,2,33,4,4,11,22,3,3,2]
list5

[1, 2, 2, 33, 4, 4, 11, 22, 3, 3, 2]

In [180]:
set(list5)

TypeError: 'list' object is not callable

### Membership Operator

In [181]:
m='zhipatnha'
m

'zhipatnha'

In [182]:
'p' in m

True

In [183]:
't' not in m

False

In [184]:
x=100
y=100
x is y

True

In [185]:
x is not y

False

In [191]:
list1=[1,2,3]
list2=[1,2,3]
list1 == list2

True

### Numerical Python

In [192]:
import numpy as np

In [193]:
x=[1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [194]:
type(x)

list

In [197]:
y=np.array(x)


In [196]:
type(y)

numpy.ndarray

In [199]:
x2=(1,2,3,'NIELT',3.4)

In [200]:
np.array(x2)

array(['1', '2', '3', 'NIELT', '3.4'], dtype='<U11')

#### Linspace

In [201]:
np.linspace(start=0, stop=20, num=10, endpoint=False,retstep=True)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [202]:
np.linspace(start=0, stop=20, num=10, endpoint=True,retstep=True)

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

### Arange

In [208]:
np.arange(start=0,stop=50,step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [209]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [210]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [211]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

### Create 3D Array

In [213]:
z=[[1,2,3],[4,5,6],[7,8,9]]

In [214]:
z

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [216]:
y=np.array(z)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [217]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [218]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [219]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Reshaping

In [220]:
x=np.array([0,1,2,3,4,5,6,7,8,9])

In [221]:
x #1*10 type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Convert to 5*2

In [222]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [223]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [224]:
x.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [225]:
x.reshape((2,10))

ValueError: cannot reshape array of size 10 into shape (2,10)

In [226]:
x.reshape((1,5))

ValueError: cannot reshape array of size 10 into shape (1,5)

### Slicing

In [227]:
a=np.arange(10)

In [228]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [229]:
s=slice(2,7)

In [230]:
a[s]

array([2, 3, 4, 5, 6])

In [231]:
s1=slice(2,7,2)

In [232]:
a[s1]

array([2, 4, 6])

In [233]:
a[2:7]

array([2, 3, 4, 5, 6])

In [234]:
a[2:7:2]

array([2, 4, 6])

### Random Number Generation

In [235]:
np.random.rand(5)

array([0.18265129, 0.29393773, 0.14736933, 0.16362737, 0.37553711])

In [236]:
np.random.rand(5)

array([0.31424263, 0.12140758, 0.17875496, 0.54021827, 0.47968657])

###  Normal Distribution

In [237]:
np.random.rand(5,4)

array([[0.6798903 , 0.63775073, 0.15759076, 0.42845587],
       [0.24344611, 0.53513079, 0.79871942, 0.58015344],
       [0.46002239, 0.60482266, 0.61798459, 0.43068633],
       [0.50339941, 0.82536477, 0.94254218, 0.71275649],
       [0.31683384, 0.84003806, 0.88147157, 0.32666979]])

### Randint

In [242]:
np.random.randint(low=0,high=100)

51

In [243]:
# 4 digit Random Number
np.random.randint(low=1000,high=9999)

7149

In [244]:
np.random.randint(low=1000,high=9999,size=10)

array([4954, 5514, 4734, 9405, 1784, 6961, 3847, 8562, 4077, 2580])

### Seed

In [245]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [246]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [247]:
np.random.seed(23)
np.random.randint(low=1000,high=9999)

9787

In [248]:
np.random.randint(low=1000,high=9999)
np.random.seed(23)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])